name: Release

on:
  release:
    types: [ published ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Publish plugins
        uses: gradle/gradle-command-action@v2
        with:
          arguments: publish -Pversion=${{ steps.version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          DEPLOYER_PASSWORD: ${{ secrets.DEPLOYER_PASSWORD }}
  ping:
    name: Notify Upstream Repositories
    runs-on: ubuntu-latest
    needs: [ release ]
    strategy:
      matrix:
        repository:
          - agorapulse/agorapulse-bom
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Dispatch to ${{ matrix.repository }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: ap-new-version-released-event
          client-payload: '{ "group": "com.agorapulse", "module": "notification", "version": "${{ steps.version.outputs.tag }}", "property" : "grails.facebook.sdk.version", "github" : ${{ toJson(github) }} }'
