name: Release

on:
  push:
    tags:
    - '*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Semantic Version
      id: version
      uses: ncipollo/semantic-version-action@v1
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: bintrayUpload -PbintrayUser=${{ env.BINTRAY_USER }} -PbintrayKey=${{ secrets.BINTRAY_KEY }}  -Pversion=${{ steps.version.outputs.tag }} --stacktrace
